services:
  keycloak:
    container_name: keycloak-demo
    image: quay.io/keycloak/keycloak:latest
    restart: always
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_PORT: 8081
      #KC_LOG_LEVEL: DEBUG
      KC_DB: postgres
      KC_DB_URL_HOST: db
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: demo
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: 123
      KC_DB_SCHEMA: keycloak
    ports:
      - "8081:8081"
    command:
      - start-dev
    depends_on:
      adminer:
        condition: service_started
    networks:
      - demo_network
  db:
    image: postgres:12-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=demo
    command: 'docker-entrypoint.sh postgres'
    volumes:
      - ./docker/db/shared_data:/var/lib/postgresql/data
      - ./docker/db/script:/docker-entrypoint-initdb.d
    ports:
      - '1234:5432'
    healthcheck:
      test: "exist 0"
    networks:
      - demo_network
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - demo_network
    depends_on:
      db:
        condition: service_started
networks:
  demo_network:
    driver: bridge
